<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Ingredient;

class IngredientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ingredients = [
            // Carnes e Proteínas
            ['name' => 'Frango', 'default_unit' => 'unidade'],
            ['name' => 'Peito de Frango', 'default_unit' => 'unidade'],
            ['name' => 'Coxa de Frango', 'default_unit' => 'unidade'],
            ['name' => 'Sobrecoxa de Frango', 'default_unit' => 'unidade'],
            ['name' => 'Carne Bovina', 'default_unit' => 'unidade'],
            ['name' => 'Alcatra', 'default_unit' => 'unidade'],
            ['name' => 'Picanha', 'default_unit' => 'unidade'],
            ['name' => 'Contrafilé', 'default_unit' => 'unidade'],
            ['name' => 'Patinho', 'default_unit' => 'unidade'],
            ['name' => 'Coxão Mole', 'default_unit' => 'unidade'],
            ['name' => 'Carne Moída', 'default_unit' => 'unidade'],
            ['name' => 'Carne Suína', 'default_unit' => 'unidade'],
            ['name' => 'Lombo Suíno', 'default_unit' => 'unidade'],
            ['name' => 'Costela Suína', 'default_unit' => 'unidade'],
            ['name' => 'Peixe', 'default_unit' => 'unidade'],
            ['name' => 'Salmão', 'default_unit' => 'unidade'],
            ['name' => 'Tilápia', 'default_unit' => 'unidade'],
            ['name' => 'Bacalhau', 'default_unit' => 'unidade'],
            ['name' => 'Sardinha', 'default_unit' => 'unidade'],
            ['name' => 'Camarão', 'default_unit' => 'unidade'],
            ['name' => 'Lula', 'default_unit' => 'unidade'],
            ['name' => 'Ovos', 'default_unit' => 'unidade'],
            ['name' => 'Bacon', 'default_unit' => 'unidade'],
            ['name' => 'Linguiça', 'default_unit' => 'unidade'],
            ['name' => 'Linguiça Calabresa', 'default_unit' => 'unidade'],
            ['name' => 'Linguiça Toscana', 'default_unit' => 'unidade'],
            ['name' => 'Presunto', 'default_unit' => 'unidade'],
            ['name' => 'Peito de Peru', 'default_unit' => 'unidade'],
            ['name' => 'Salsicha', 'default_unit' => 'unidade'],
            ['name' => 'Mortadela', 'default_unit' => 'unidade'],

            // Laticínios
            ['name' => 'Leite', 'default_unit' => 'unidade'],
            ['name' => 'Leite Integral', 'default_unit' => 'unidade'],
            ['name' => 'Leite Desnatado', 'default_unit' => 'unidade'],
            ['name' => 'Creme de Leite', 'default_unit' => 'unidade'],
            ['name' => 'Leite Condensado', 'default_unit' => 'unidade'],
            ['name' => 'Leite de Coco', 'default_unit' => 'unidade'],
            ['name' => 'Iogurte Natural', 'default_unit' => 'unidade'],
            ['name' => 'Iogurte Grego', 'default_unit' => 'unidade'],
            ['name' => 'Queijo Mussarela', 'default_unit' => 'unidade'],
            ['name' => 'Queijo Parmesão', 'default_unit' => 'unidade'],
            ['name' => 'Queijo Prato', 'default_unit' => 'unidade'],
            ['name' => 'Queijo Cheddar', 'default_unit' => 'unidade'],
            ['name' => 'Queijo Gorgonzola', 'default_unit' => 'unidade'],
            ['name' => 'Queijo Ricota', 'default_unit' => 'unidade'],
            ['name' => 'Queijo Cottage', 'default_unit' => 'unidade'],
            ['name' => 'Queijo Minas', 'default_unit' => 'unidade'],
            ['name' => 'Requeijão', 'default_unit' => 'unidade'],
            ['name' => 'Manteiga', 'default_unit' => 'unidade'],
            ['name' => 'Margarina', 'default_unit' => 'unidade'],
            ['name' => 'Nata', 'default_unit' => 'unidade'],

            // Vegetais e Verduras
            ['name' => 'Cebola', 'default_unit' => 'unidade'],
            ['name' => 'Cebola Roxa', 'default_unit' => 'unidade'],
            ['name' => 'Cebolinha', 'default_unit' => 'unidade'],
            ['name' => 'Alho', 'default_unit' => 'unidade'],
            ['name' => 'Alho-poró', 'default_unit' => 'unidade'],
            ['name' => 'Tomate', 'default_unit' => 'unidade'],
            ['name' => 'Tomate Cereja', 'default_unit' => 'unidade'],
            ['name' => 'Tomate Seco', 'default_unit' => 'unidade'],
            ['name' => 'Cenoura', 'default_unit' => 'unidade'],
            ['name' => 'Batata', 'default_unit' => 'unidade'],
            ['name' => 'Batata Doce', 'default_unit' => 'unidade'],
            ['name' => 'Batata Inglesa', 'default_unit' => 'unidade'],
            ['name' => 'Mandioca', 'default_unit' => 'unidade'],
            ['name' => 'Inhame', 'default_unit' => 'unidade'],
            ['name' => 'Abobrinha', 'default_unit' => 'unidade'],
            ['name' => 'Abóbora', 'default_unit' => 'unidade'],
            ['name' => 'Berinjela', 'default_unit' => 'unidade'],
            ['name' => 'Pimentão', 'default_unit' => 'unidade'],
            ['name' => 'Pimentão Vermelho', 'default_unit' => 'unidade'],
            ['name' => 'Pimentão Amarelo', 'default_unit' => 'unidade'],
            ['name' => 'Pimenta Dedo-de-moça', 'default_unit' => 'unidade'],
            ['name' => 'Pimenta Malagueta', 'default_unit' => 'unidade'],
            ['name' => 'Brócolis', 'default_unit' => 'unidade'],
            ['name' => 'Couve-flor', 'default_unit' => 'unidade'],
            ['name' => 'Alface', 'default_unit' => 'unidade'],
            ['name' => 'Rúcula', 'default_unit' => 'unidade'],
            ['name' => 'Espinafre', 'default_unit' => 'unidade'],
            ['name' => 'Couve', 'default_unit' => 'unidade'],
            ['name' => 'Couve Manteiga', 'default_unit' => 'unidade'],
            ['name' => 'Repolho', 'default_unit' => 'unidade'],
            ['name' => 'Repolho Roxo', 'default_unit' => 'unidade'],
            ['name' => 'Acelga', 'default_unit' => 'unidade'],
            ['name' => 'Agrião', 'default_unit' => 'unidade'],
            ['name' => 'Almeirão', 'default_unit' => 'unidade'],
            ['name' => 'Chicória', 'default_unit' => 'unidade'],
            ['name' => 'Pepino', 'default_unit' => 'unidade'],
            ['name' => 'Aipo', 'default_unit' => 'unidade'],
            ['name' => 'Salsão', 'default_unit' => 'unidade'],
            ['name' => 'Beterraba', 'default_unit' => 'unidade'],
            ['name' => 'Rabanete', 'default_unit' => 'unidade'],
            ['name' => 'Nabo', 'default_unit' => 'unidade'],
            ['name' => 'Chuchu', 'default_unit' => 'unidade'],
            ['name' => 'Quiabo', 'default_unit' => 'unidade'],
            ['name' => 'Jiló', 'default_unit' => 'unidade'],
            ['name' => 'Maxixe', 'default_unit' => 'unidade'],
            ['name' => 'Vagem', 'default_unit' => 'unidade'],
            ['name' => 'Ervilha', 'default_unit' => 'unidade'],
            ['name' => 'Milho', 'default_unit' => 'unidade'],
            ['name' => 'Milho Verde', 'default_unit' => 'unidade'],

            // Frutas
            ['name' => 'Banana', 'default_unit' => 'unidade'],
            ['name' => 'Banana Nanica', 'default_unit' => 'unidade'],
            ['name' => 'Banana Prata', 'default_unit' => 'unidade'],
            ['name' => 'Maçã', 'default_unit' => 'unidade'],
            ['name' => 'Maçã Verde', 'default_unit' => 'unidade'],
            ['name' => 'Laranja', 'default_unit' => 'unidade'],
            ['name' => 'Laranja Lima', 'default_unit' => 'unidade'],
            ['name' => 'Limão', 'default_unit' => 'unidade'],
            ['name' => 'Limão Siciliano', 'default_unit' => 'unidade'],
            ['name' => 'Lima da Pérsia', 'default_unit' => 'unidade'],
            ['name' => 'Morango', 'default_unit' => 'unidade'],
            ['name' => 'Uva', 'default_unit' => 'unidade'],
            ['name' => 'Uva Passa', 'default_unit' => 'unidade'],
            ['name' => 'Abacaxi', 'default_unit' => 'unidade'],
            ['name' => 'Manga', 'default_unit' => 'unidade'],
            ['name' => 'Mamão', 'default_unit' => 'unidade'],
            ['name' => 'Melancia', 'default_unit' => 'unidade'],
            ['name' => 'Melão', 'default_unit' => 'unidade'],
            ['name' => 'Pêra', 'default_unit' => 'unidade'],
            ['name' => 'Pêssego', 'default_unit' => 'unidade'],
            ['name' => 'Ameixa', 'default_unit' => 'unidade'],
            ['name' => 'Kiwi', 'default_unit' => 'unidade'],
            ['name' => 'Abacate', 'default_unit' => 'unidade'],
            ['name' => 'Coco', 'default_unit' => 'unidade'],
            ['name' => 'Coco Ralado', 'default_unit' => 'unidade'],
            ['name' => 'Maracujá', 'default_unit' => 'unidade'],
            ['name' => 'Goiaba', 'default_unit' => 'unidade'],
            ['name' => 'Caju', 'default_unit' => 'unidade'],
            ['name' => 'Acerola', 'default_unit' => 'unidade'],
            ['name' => 'Pitanga', 'default_unit' => 'unidade'],
            ['name' => 'Jabuticaba', 'default_unit' => 'unidade'],
            ['name' => 'Caqui', 'default_unit' => 'unidade'],
            ['name' => 'Figo', 'default_unit' => 'unidade'],
            ['name' => 'Romã', 'default_unit' => 'unidade'],
            ['name' => 'Manga', 'default_unit' => 'unidade'],
            ['name' => 'Mamão', 'default_unit' => 'unidade'],

            // Grãos e Cereais
            ['name' => 'Arroz', 'default_unit' => 'unidade'],
            ['name' => 'Arroz Branco', 'default_unit' => 'unidade'],
            ['name' => 'Arroz Integral', 'default_unit' => 'unidade'],
            ['name' => 'Arroz Parboilizado', 'default_unit' => 'unidade'],
            ['name' => 'Feijão', 'default_unit' => 'unidade'],
            ['name' => 'Feijão Preto', 'default_unit' => 'unidade'],
            ['name' => 'Feijão Carioca', 'default_unit' => 'unidade'],
            ['name' => 'Feijão Fradinho', 'default_unit' => 'unidade'],
            ['name' => 'Feijão Branco', 'default_unit' => 'unidade'],
            ['name' => 'Lentilha', 'default_unit' => 'unidade'],
            ['name' => 'Grão de Bico', 'default_unit' => 'unidade'],
            ['name' => 'Ervilha Seca', 'default_unit' => 'unidade'],
            ['name' => 'Soja', 'default_unit' => 'unidade'],
            ['name' => 'Quinoa', 'default_unit' => 'unidade'],
            ['name' => 'Aveia', 'default_unit' => 'unidade'],
            ['name' => 'Aveia em Flocos', 'default_unit' => 'unidade'],
            ['name' => 'Farelo de Aveia', 'default_unit' => 'unidade'],
            ['name' => 'Farinha de Trigo', 'default_unit' => 'unidade'],
            ['name' => 'Farinha Integral', 'default_unit' => 'unidade'],
            ['name' => 'Farinha de Rosca', 'default_unit' => 'unidade'],
            ['name' => 'Farinha de Mandioca', 'default_unit' => 'unidade'],
            ['name' => 'Farinha de Milho', 'default_unit' => 'unidade'],
            ['name' => 'Fubá', 'default_unit' => 'unidade'],
            ['name' => 'Polvilho Doce', 'default_unit' => 'unidade'],
            ['name' => 'Polvilho Azedo', 'default_unit' => 'unidade'],
            ['name' => 'Amido de Milho', 'default_unit' => 'unidade'],
            ['name' => 'Tapioca', 'default_unit' => 'unidade'],

            // Massas
            ['name' => 'Macarrão Espaguete', 'default_unit' => 'unidade'],
            ['name' => 'Macarrão Penne', 'default_unit' => 'unidade'],
            ['name' => 'Macarrão Parafuso', 'default_unit' => 'unidade'],
            ['name' => 'Macarrão Talharim', 'default_unit' => 'unidade'],
            ['name' => 'Macarrão Linguine', 'default_unit' => 'unidade'],
            ['name' => 'Macarrão Farfalle', 'default_unit' => 'unidade'],
            ['name' => 'Lasanha', 'default_unit' => 'unidade'],
            ['name' => 'Nhoque', 'default_unit' => 'unidade'],
            ['name' => 'Massa de Pastel', 'default_unit' => 'unidade'],
            ['name' => 'Massa Folhada', 'default_unit' => 'unidade'],

            // Temperos e Condimentos
            ['name' => 'Sal', 'default_unit' => 'unidade'],
            ['name' => 'Sal Grosso', 'default_unit' => 'unidade'],
            ['name' => 'Sal Refinado', 'default_unit' => 'unidade'],
            ['name' => 'Pimenta do Reino', 'default_unit' => 'unidade'],
            ['name' => 'Pimenta Branca', 'default_unit' => 'unidade'],
            ['name' => 'Orégano', 'default_unit' => 'unidade'],
            ['name' => 'Manjericão', 'default_unit' => 'unidade'],
            ['name' => 'Manjericão Seco', 'default_unit' => 'unidade'],
            ['name' => 'Salsa', 'default_unit' => 'unidade'],
            ['name' => 'Cebolinha Verde', 'default_unit' => 'unidade'],
            ['name' => 'Coentro', 'default_unit' => 'unidade'],
            ['name' => 'Cominho', 'default_unit' => 'unidade'],
            ['name' => 'Páprica', 'default_unit' => 'unidade'],
            ['name' => 'Páprica Doce', 'default_unit' => 'unidade'],
            ['name' => 'Páprica Picante', 'default_unit' => 'unidade'],
            ['name' => 'Açafrão', 'default_unit' => 'unidade'],
            ['name' => 'Açafrão da Terra', 'default_unit' => 'unidade'],
            ['name' => 'Canela em Pó', 'default_unit' => 'unidade'],
            ['name' => 'Canela em Pau', 'default_unit' => 'unidade'],
            ['name' => 'Cravo da Índia', 'default_unit' => 'unidade'],
            ['name' => 'Noz Moscada', 'default_unit' => 'unidade'],
            ['name' => 'Gengibre', 'default_unit' => 'unidade'],
            ['name' => 'Alecrim', 'default_unit' => 'unidade'],
            ['name' => 'Tomilho', 'default_unit' => 'unidade'],
            ['name' => 'Louro', 'default_unit' => 'unidade'],
            ['name' => 'Curry', 'default_unit' => 'unidade'],
            ['name' => 'Mostarda em Grão', 'default_unit' => 'unidade'],
            ['name' => 'Mostarda', 'default_unit' => 'unidade'],
            ['name' => 'Ketchup', 'default_unit' => 'unidade'],
            ['name' => 'Maionese', 'default_unit' => 'unidade'],
            ['name' => 'Molho de Soja', 'default_unit' => 'unidade'],
            ['name' => 'Molho Inglês', 'default_unit' => 'unidade'],
            ['name' => 'Molho de Pimenta', 'default_unit' => 'unidade'],

            // Óleos e Vinagres
            ['name' => 'Azeite de Oliva', 'default_unit' => 'unidade'],
            ['name' => 'Azeite Extra Virgem', 'default_unit' => 'unidade'],
            ['name' => 'Óleo de Soja', 'default_unit' => 'unidade'],
            ['name' => 'Óleo de Girassol', 'default_unit' => 'unidade'],
            ['name' => 'Óleo de Milho', 'default_unit' => 'unidade'],
            ['name' => 'Óleo de Coco', 'default_unit' => 'unidade'],
            ['name' => 'Vinagre Branco', 'default_unit' => 'unidade'],
            ['name' => 'Vinagre de Maçã', 'default_unit' => 'unidade'],
            ['name' => 'Vinagre Balsâmico', 'default_unit' => 'unidade'],
            ['name' => 'Vinagre de Vinho', 'default_unit' => 'unidade'],

            // Açúcares e Adoçantes
            ['name' => 'Açúcar Cristal', 'default_unit' => 'unidade'],
            ['name' => 'Açúcar Refinado', 'default_unit' => 'unidade'],
            ['name' => 'Açúcar Mascavo', 'default_unit' => 'unidade'],
            ['name' => 'Açúcar Demerara', 'default_unit' => 'unidade'],
            ['name' => 'Açúcar de Confeiteiro', 'default_unit' => 'unidade'],
            ['name' => 'Mel', 'default_unit' => 'unidade'],
            ['name' => 'Melado', 'default_unit' => 'unidade'],
            ['name' => 'Xarope de Milho', 'default_unit' => 'unidade'],

            // Oleaginosas e Sementes
            ['name' => 'Amendoim', 'default_unit' => 'unidade'],
            ['name' => 'Castanha do Pará', 'default_unit' => 'unidade'],
            ['name' => 'Castanha de Caju', 'default_unit' => 'unidade'],
            ['name' => 'Nozes', 'default_unit' => 'unidade'],
            ['name' => 'Amêndoas', 'default_unit' => 'unidade'],
            ['name' => 'Pistache', 'default_unit' => 'unidade'],
            ['name' => 'Avelã', 'default_unit' => 'unidade'],
            ['name' => 'Gergelim', 'default_unit' => 'unidade'],
            ['name' => 'Linhaça', 'default_unit' => 'unidade'],
            ['name' => 'Chia', 'default_unit' => 'unidade'],
            ['name' => 'Girassol', 'default_unit' => 'unidade'],

            // Outros
            ['name' => 'Água', 'default_unit' => 'unidade'],
            ['name' => 'Caldo de Galinha', 'default_unit' => 'unidade'],
            ['name' => 'Caldo de Legumes', 'default_unit' => 'unidade'],
            ['name' => 'Vinho Branco', 'default_unit' => 'unidade'],
            ['name' => 'Vinho Tinto', 'default_unit' => 'unidade'],
            ['name' => 'Cerveja', 'default_unit' => 'unidade'],
            ['name' => 'Fermento em Pó', 'default_unit' => 'unidade'],
            ['name' => 'Bicarbonato de Sódio', 'default_unit' => 'unidade'],
            ['name' => 'Gelatina sem Sabor', 'default_unit' => 'unidade'],
        ];

        foreach ($ingredients as $ingredient) {
            Ingredient::firstOrCreate(
                ['name' => $ingredient['name']],
                $ingredient
            );
        }
    }
}